/* Generated by re2c 1.3 on Tue Apr 20 22:38:58 2021 */
#line 1 "sexpr_parse.c.re"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include "sexpr_parse.h"


static void
push(struct parse_state *ps,  uintptr_t c)
{
        uintptr_t *ts = ps->stack + ps->sptr++;
        struct centry *ctop =  ps->control_stack + ps->csptr - 1;
        *ts = c;
        while (ctop->unary && ps->sptr - 1 == ctop->depth) {
                *ts = sp_unary(ps, ctop->what, *ts);
                ctop--; ps->csptr--;
        }
}


static void
push_control(struct parse_state *ps, char control)
{
        struct centry *ctop = ps->control_stack + ps->csptr++;
        ctop->what = control;
        ctop->unary = control != '(' && control != '.';
        ctop->depth = ps->sptr;
}

static int
close_enclosed(struct parse_state *ps, char control)
{
        struct centry *ctop = ps->control_stack + ps->csptr - 1;
        bool is_cons = false;
        uintptr_t cdr = 0;
        int sptr = ps->sptr;
        if (ctop->what == '.') {
                ps->csptr--;
                int len = sptr - ctop->depth;
                if (len != 1) {
                        if (ps->fname)
                                printf("%s:%i: ", ps->fname, ps->lineno);
                        printf("bad cons tail %i\n", len);
                        return 6;
                }
                cdr = ps->stack[--sptr];
                ctop--;
                is_cons = true;
        }
        if (ctop->what == '(') {
                ps->csptr--;
                int len = sptr - ctop->depth;
                uintptr_t v = is_cons
                              ?  sp_cons(ps, ctop->what, &ps->stack[sptr - len], len, cdr)
                              :  sp_list(ps, ctop->what, &ps->stack[sptr - len], len);
                ps->sptr = sptr - len;
                push(ps, v);
                return 0;
        }
        if (ps->fname)
                printf("%s:%i: ", ps->fname, ps->lineno);
        printf("bad closing %c %02x\n", ctop->what, ctop->what);
        return 5;
}


int
scan(struct parse_state *ps, char *start)
{
        ps->cursor = ps->start = start;
        char *t;
        int res = 0;
        char *YYMARKER;
        while (!res) {
                t = ps->cursor;
                
#line 80 "sexpr_parse.c"
		{
			unsigned char curr;
			unsigned int yyaccept = 0;
			curr = (unsigned char)*ps->cursor;
			switch (curr) {
			case 0x00:	goto scan2;
			case '\t':
			case '\r':
			case ' ':	goto scan6;
			case '\n':	goto scan9;
			case '!':
			case '$':
			case '%':
			case '&':
			case '*':
			case '/':
			case ':':
			case '<':
			case '=':
			case '>':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '^':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':
			case '~':	goto scan11;
			case '"':	goto scan14;
			case '#':	goto scan15;
			case '\'':
			case '(':
			case '`':	goto scan17;
			case ')':	goto scan18;
			case '+':	goto scan20;
			case ',':	goto scan22;
			case '-':	goto scan23;
			case '.':	goto scan25;
			case '0':	goto scan26;
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto scan28;
			case ';':	goto scan30;
			default:	goto scan4;
			}
scan2:
			++ps->cursor;
#line 93 "sexpr_parse.c.re"
			{ res = ps->sptr == 1 ? 0 : 2;  break; }
#line 184 "sexpr_parse.c"
scan4:
			++ps->cursor;
scan5:
#line 109 "sexpr_parse.c.re"
			{ if (ps->fname) printf("%s:%i: ", ps->fname, ps->lineno); printf("unknown character %c\n", *t); res = 1;  continue; }
#line 190 "sexpr_parse.c"
scan6:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
			case '\t':
			case '\r':
			case ' ':	goto scan6;
			default:	goto scan8;
			}
scan8:
#line 96 "sexpr_parse.c.re"
			{ continue; }
#line 202 "sexpr_parse.c"
scan9:
			++ps->cursor;
#line 95 "sexpr_parse.c.re"
			{ ps->lineno++; continue; }
#line 207 "sexpr_parse.c"
scan11:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
			case '!':
			case '$':
			case '%':
			case '&':
			case '*':
			case '+':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case ':':
			case '<':
			case '=':
			case '>':
			case '?':
			case '@':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '^':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':
			case '~':	goto scan11;
			default:	goto scan13;
			}
scan13:
#line 97 "sexpr_parse.c.re"
			{ push(ps, sp_symbol(ps, t, ps->cursor)); continue; }
#line 296 "sexpr_parse.c"
scan14:
			yyaccept = 0;
			curr = (unsigned char)*(YYMARKER = ++ps->cursor);
			if (curr <= 0x00) goto scan5;
			goto scan34;
scan15:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
			case ';':	goto scan40;
			default:	goto scan16;
			}
scan16:
#line 107 "sexpr_parse.c.re"
			{ push_control(ps, *t); continue; }
#line 311 "sexpr_parse.c"
scan17:
			++ps->cursor;
			goto scan16;
scan18:
			++ps->cursor;
#line 108 "sexpr_parse.c.re"
			{ res = close_enclosed(ps, *t); continue; }
#line 319 "sexpr_parse.c"
scan20:
			++ps->cursor;
#line 103 "sexpr_parse.c.re"
			{ push(ps, sp_symbol(ps, t, ps->cursor)); continue; }
#line 324 "sexpr_parse.c"
scan22:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
			case '@':	goto scan42;
			default:	goto scan16;
			}
scan23:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
			case '0':	goto scan26;
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto scan28;
			default:	goto scan24;
			}
scan24:
#line 104 "sexpr_parse.c.re"
			{ push(ps, sp_symbol(ps, t, ps->cursor)); continue; }
#line 349 "sexpr_parse.c"
scan25:
			yyaccept = 1;
			curr = (unsigned char)*(YYMARKER = ++ps->cursor);
			switch (curr) {
			case '.':	goto scan44;
			default:	goto scan16;
			}
scan26:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto scan45;
			default:	goto scan27;
			}
scan27:
#line 100 "sexpr_parse.c.re"
			{ push(ps, sp_number(ps, t, ps->cursor, 10)); continue; }
#line 375 "sexpr_parse.c"
scan28:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto scan28;
			default:	goto scan27;
			}
scan30:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
			case 0x00:
			case '\n':	goto scan32;
			default:	goto scan30;
			}
scan32:
#line 94 "sexpr_parse.c.re"
			{ continue; }
#line 401 "sexpr_parse.c"
scan33:
			curr = (unsigned char)*++ps->cursor;
scan34:
			switch (curr) {
			case 0x00:	goto scan35;
			case '"':	goto scan36;
			case '\\':	goto scan38;
			default:	goto scan33;
			}
scan35:
			ps->cursor = YYMARKER;
			switch (yyaccept) {
			case 0: 	goto scan5;
			case 1: 	goto scan16;
			default:	goto scan37;
			}
scan36:
			++ps->cursor;
scan37:
#line 98 "sexpr_parse.c.re"
			{ push(ps, sp_string(ps, t, ps->cursor)); continue; }
#line 423 "sexpr_parse.c"
scan38:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
			case 0x00:	goto scan35;
			case '"':	goto scan48;
			case '\\':	goto scan38;
			default:	goto scan33;
			}
scan40:
			++ps->cursor;
#line 106 "sexpr_parse.c.re"
			{ push_control(ps, ';'); continue; }
#line 436 "sexpr_parse.c"
scan42:
			++ps->cursor;
#line 105 "sexpr_parse.c.re"
			{ push_control(ps, '@'); continue; }
#line 441 "sexpr_parse.c"
scan44:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
			case '.':	goto scan49;
			default:	goto scan35;
			}
scan45:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto scan45;
			default:	goto scan47;
			}
scan47:
#line 99 "sexpr_parse.c.re"
			{ push(ps, sp_number(ps, t, ps->cursor, 8)); continue; }
#line 466 "sexpr_parse.c"
scan48:
			yyaccept = 2;
			curr = (unsigned char)*(YYMARKER = ++ps->cursor);
			switch (curr) {
			case 0x00:	goto scan37;
			case '"':	goto scan36;
			case '\\':	goto scan38;
			default:	goto scan33;
			}
scan49:
			++ps->cursor;
#line 102 "sexpr_parse.c.re"
			{ push(ps, sp_symbol(ps, t, ps->cursor)); continue; }
#line 480 "sexpr_parse.c"
		}
#line 110 "sexpr_parse.c.re"

        }
        return res;
}
