/* Generated by re2c 3.1 on Sat Feb 14 15:39:16 2026 */
#line 1 "sexpr_parse.c.re"
#include "sexpr_parse.h"
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>


static void
push(struct parse_state *ps,  sp_cell_t c)
{
        sp_cell_t *ts = ps->stack + ps->sptr++;
        struct centry *ctop =  ps->control_stack + ps->csptr - 1;
        *ts = c;
        while (ctop->unary && ps->sptr - 1 == ctop->depth) {
                *ts = sp_unary(ps, ctop->what, *ts);
                ctop--; ps->csptr--;
        }
}


static void
push_control(struct parse_state *ps, char control)
{
        struct centry *ctop = ps->control_stack + ps->csptr++;
        ctop->what = control;
        ctop->unary = control != '(' && control != '.';
        ctop->depth = ps->sptr;
}

static int
close_enclosed(struct parse_state *ps, char control)
{
        struct centry *ctop = ps->control_stack + ps->csptr - 1;
        bool is_cons = false;
        sp_cell_t cdr = 0;
        int sptr = ps->sptr;
        if (ctop->what == '.') {
                ps->csptr--;
                int len = sptr - ctop->depth;
                if (len != 1) {
                        if (ps->fname)
                                printf("%s:%i: ", ps->fname, ps->lineno);
                        printf("bad cons tail %i\n", len);
                        return 6;
                }
                cdr = ps->stack[--sptr];
                ctop--;
                is_cons = true;
        }
        if (ctop->what == '(') {
                ps->csptr--;
                int len = sptr - ctop->depth;
                sp_cell_t v = is_cons
                              ?  sp_cons(ps, ctop->what, &ps->stack[sptr - len], len, cdr)
                              :  sp_list(ps, ctop->what, &ps->stack[sptr - len], len);
                ps->sptr = sptr - len;
                push(ps, v);
                return 0;
        }
        if (ps->fname)
                printf("%s:%i: ", ps->fname, ps->lineno);
        printf("bad closing %c %02x\n", ctop->what, ctop->what);
        return 5;
}


int
scan(struct parse_state *ps, char *start)
{
        ps->cursor = ps->start = start;
        char *t;
        int res = 0;
        char *YYMARKER;
        while (!res) {
                t = ps->cursor;
                
#line 81 "sexpr_parse.c"
		{
			unsigned char curr;
			unsigned int yyaccept = 0;
			curr = (unsigned char)*ps->cursor;
			switch (curr) {
				case 0x00: goto scan1;
				case '\t':
				case '\r':
				case ' ': goto scan4;
				case '\n': goto scan6;
				case '!':
				case '$':
				case '%':
				case '&':
				case '*':
				case '/':
				case ':':
				case '<':
				case '=':
				case '>':
				case '?':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '^':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
				case '~': goto scan7;
				case '"': goto scan9;
				case '#': goto scan10;
				case '\'':
				case '(':
				case '`': goto scan12;
				case ')': goto scan13;
				case '+': goto scan14;
				case ',': goto scan15;
				case '-': goto scan16;
				case '.': goto scan18;
				case '0': goto scan19;
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto scan21;
				case ';': goto scan22;
				default: goto scan2;
			}
scan1:
			++ps->cursor;
#line 94 "sexpr_parse.c.re"
			{ res = ps->sptr == 1 ? 0 : 2;  break; }
#line 185 "sexpr_parse.c"
scan2:
			++ps->cursor;
scan3:
#line 110 "sexpr_parse.c.re"
			{ int r = sp_error(ps, ps->fname, ps->lineno, *t); if (r < 0) return r; }
#line 191 "sexpr_parse.c"
scan4:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
				case '\t':
				case '\r':
				case ' ': goto scan4;
				default: goto scan5;
			}
scan5:
#line 97 "sexpr_parse.c.re"
			{ continue; }
#line 203 "sexpr_parse.c"
scan6:
			++ps->cursor;
#line 96 "sexpr_parse.c.re"
			{ ps->lineno++; continue; }
#line 208 "sexpr_parse.c"
scan7:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
				case '!':
				case '$':
				case '%':
				case '&':
				case '*':
				case '+':
				case '-':
				case '.':
				case '/':
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case '<':
				case '=':
				case '>':
				case '?':
				case '@':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '^':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
				case '~': goto scan7;
				default: goto scan8;
			}
scan8:
#line 98 "sexpr_parse.c.re"
			{ push(ps, sp_symbol(ps, t, ps->cursor)); continue; }
#line 297 "sexpr_parse.c"
scan9:
			yyaccept = 0;
			curr = (unsigned char)*(YYMARKER = ++ps->cursor);
			if (curr <= 0x00) goto scan3;
			goto scan25;
scan10:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
				case ';': goto scan30;
				default: goto scan11;
			}
scan11:
#line 108 "sexpr_parse.c.re"
			{ push_control(ps, *t); continue; }
#line 312 "sexpr_parse.c"
scan12:
			++ps->cursor;
			goto scan11;
scan13:
			++ps->cursor;
#line 109 "sexpr_parse.c.re"
			{ res = close_enclosed(ps, *t); continue; }
#line 320 "sexpr_parse.c"
scan14:
			++ps->cursor;
#line 104 "sexpr_parse.c.re"
			{ push(ps, sp_symbol(ps, t, ps->cursor)); continue; }
#line 325 "sexpr_parse.c"
scan15:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
				case '@': goto scan31;
				default: goto scan11;
			}
scan16:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
				case '0': goto scan19;
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto scan21;
				default: goto scan17;
			}
scan17:
#line 105 "sexpr_parse.c.re"
			{ push(ps, sp_symbol(ps, t, ps->cursor)); continue; }
#line 350 "sexpr_parse.c"
scan18:
			yyaccept = 1;
			curr = (unsigned char)*(YYMARKER = ++ps->cursor);
			switch (curr) {
				case '.': goto scan32;
				default: goto scan11;
			}
scan19:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto scan33;
				default: goto scan20;
			}
scan20:
#line 101 "sexpr_parse.c.re"
			{ push(ps, sp_number(ps, t, ps->cursor, 10)); continue; }
#line 376 "sexpr_parse.c"
scan21:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto scan21;
				default: goto scan20;
			}
scan22:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
				case 0x00:
				case '\n': goto scan23;
				default: goto scan22;
			}
scan23:
#line 95 "sexpr_parse.c.re"
			{ continue; }
#line 402 "sexpr_parse.c"
scan24:
			curr = (unsigned char)*++ps->cursor;
scan25:
			switch (curr) {
				case 0x00: goto scan26;
				case '"': goto scan27;
				case '\\': goto scan29;
				default: goto scan24;
			}
scan26:
			ps->cursor = YYMARKER;
			switch (yyaccept) {
				case 0: goto scan3;
				case 1: goto scan11;
				default: goto scan28;
			}
scan27:
			++ps->cursor;
scan28:
#line 99 "sexpr_parse.c.re"
			{ push(ps, sp_string(ps, t, ps->cursor)); continue; }
#line 424 "sexpr_parse.c"
scan29:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
				case 0x00: goto scan26;
				case '"': goto scan35;
				case '\\': goto scan29;
				default: goto scan24;
			}
scan30:
			++ps->cursor;
#line 107 "sexpr_parse.c.re"
			{ push_control(ps, ';'); continue; }
#line 437 "sexpr_parse.c"
scan31:
			++ps->cursor;
#line 106 "sexpr_parse.c.re"
			{ push_control(ps, '@'); continue; }
#line 442 "sexpr_parse.c"
scan32:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
				case '.': goto scan36;
				default: goto scan26;
			}
scan33:
			curr = (unsigned char)*++ps->cursor;
			switch (curr) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto scan33;
				default: goto scan34;
			}
scan34:
#line 100 "sexpr_parse.c.re"
			{ push(ps, sp_number(ps, t, ps->cursor, 8)); continue; }
#line 467 "sexpr_parse.c"
scan35:
			yyaccept = 2;
			curr = (unsigned char)*(YYMARKER = ++ps->cursor);
			switch (curr) {
				case 0x00: goto scan28;
				case '"': goto scan27;
				case '\\': goto scan29;
				default: goto scan24;
			}
scan36:
			++ps->cursor;
#line 103 "sexpr_parse.c.re"
			{ push(ps, sp_symbol(ps, t, ps->cursor)); continue; }
#line 481 "sexpr_parse.c"
		}
#line 111 "sexpr_parse.c.re"

        }
        return res;
}

#if SP_ERROR != 3
int sp_error(struct parse_state *ps, char *fname, int line, char unknown)
{
				if (!SP_ERROR)
								return 0;
				if (fname)
								printf("%s:%i: ", fname, line);
				else 
								printf("line %i: ", line);
				if (isprint(unknown))
								printf("unknown character '%c'\n", unknown);
				else
								printf("unknown character '\\x%02x'\n", unknown);
				return SP_ERROR == 2 ? -1 : 0;
}
#endif

